#! /bin/bash

_unreadchecker_bash_autocomplete() {
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion | perl -pe 's#(?<!\\):.*##' )

    if [[ "${opts}" == 'fileCompletion' ]]; then
        _filedir
        return
    fi

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _unreadchecker_bash_autocomplete unreadChecker
